apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-filx-dev-ks8
spec:
  replicas: 5  # Defina o número desejado de réplicas
  selector:
    matchLabels:
      app: movie-filx-dev-ks8
  template:
    metadata:
      labels:
        app: movie-filx-dev-ks8
    spec:
      containers:
      - name: movie-filx-dev-ks8
        image: jeffersonbdsantos/movie-flix:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: movie-filx-service
spec:
  selector:
    app: movie-filx-dev-ks8
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080  # Escolha uma porta no intervalo 30000-32767
  type: NodePort
